name: Build

on:
  push:
    branches: [ "master, develop" ]
  pull_request:
    branches: [ "master, develop" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
