name: Coverage

on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request:
    branches:
      - 'master'
      - 'develop'
  workflow_dispatch:
jobs:
  test:
    name: Coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install CMake
        uses: symbitic/install-cmake@master

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --no-default-features --config tarpaulin_no_wgpu.toml --timeout 120 --out html --output-dir "tarpaulin_output"

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: tarpaulin_output/tarpaulin-report.html